//@ sourceMappingURL=PlanetFarMeshShader.map
// Generated by CoffeeScript 1.6.1
(function() {
  var frag, vert;

  frag = "\nprecision mediump float;\n\nvarying vec3 vNormal;\nuniform float alpha;\nuniform vec3 lightVec;\n\nvoid main(void) {\n    gl_FragColor.xyz = vec3(0.5, 0.5, 0.5) * dot(vNormal, lightVec) + vec3(0.1, 0.2, 0.1);\n    gl_FragColor.w = alpha;\n}\n";

  vert = "\nattribute vec3 aPos;\nattribute vec2 aUV;\n\nuniform mat4 projMat;\nuniform mat4 modelViewMat;\n\nvarying vec3 vNormal;\n\nvoid main(void) {\n	vNormal = aPos + aUV.x * 0.0;\n\n	vec4 pos = vec4(aPos, 1.0);\n	pos = modelViewMat * pos;\n    gl_Position = projMat * pos;\n}\n";

  xgl.addProgram("planetFarMesh", vert, frag);

}).call(this);
