//@ sourceMappingURL=PlanetMath.map
// Generated by CoffeeScript 1.6.1
(function() {
  var initialize, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.cubeFaceQuaternion = [];

  root.mapPlaneToCube = function(u, v, faceIndex) {
    var pos;
    pos = vec3.fromValues(u * 2 - 1, v * 2 - 1, 1);
    vec3.transformQuat(pos, pos, cubeFaceQuaternion[faceIndex]);
    return pos;
  };

  initialize = function() {
    var i, unitX, unitY, _i;
    for (i = _i = 0; _i <= 5; i = ++_i) {
      cubeFaceQuaternion[i] = quat.create();
    }
    unitX = vec3.fromValues(1, 0, 0);
    unitY = vec3.fromValues(0, 1, 0);
    quat.setAxisAngle(cubeFaceQuaternion[1], unitY, xgl.degToRad(180));
    quat.setAxisAngle(cubeFaceQuaternion[2], unitY, xgl.degToRad(-90));
    quat.setAxisAngle(cubeFaceQuaternion[3], unitY, xgl.degToRad(90));
    quat.setAxisAngle(cubeFaceQuaternion[4], unitX, xgl.degToRad(90));
    return quat.setAxisAngle(cubeFaceQuaternion[5], unitX, xgl.degToRad(-90));
  };

  initialize();

}).call(this);
