//@ sourceMappingURL=PlanetNearMeshShader.map
// Generated by CoffeeScript 1.6.1
(function() {
  var frag, vert;

  frag = "\nprecision mediump float;\n\nvarying vec3 vNormal;\nvarying vec2 vUV;\n\nuniform float alpha;\nuniform vec3 lightVec;\nuniform sampler2D sampler;\n\nuniform vec4 uvRect;\n\nconst float uvScalar = 4097.0 / 4096.0;\n#define ONE_TEXEL (1.0/4096.0)\n\nfloat computeLighting(vec3 N)\n{\n	vec3 L = lightVec;\n\n	/*for (int i = 0; i < 8; ++i) {\n		tex = tex * 0.5 + texture2D(sampler, vUV * uvScalar + vec2(ONE_TEXEL, ONE_TEXEL) * float(i), -0.5) * 0.5;\n	}*/\n\n	float d = dot(N, L);\n 	return d;\n}\n\nvoid main(void) {\n	vec4 tex = texture2D(sampler, vUV * uvScalar, -0.5);\n\n	float ao = (tex.a * 0.5 + 0.5);\n	\n	// extract normal and horizon values\n	vec3 norm = normalize(tex.xyz * 2.0 - 1.0);\n\n	float l = ao * computeLighting(norm) ;//* 0.9 + 0.1;\n\n	//l = 1.0 - horizon;\n\n    gl_FragColor.xyz = vec3(l);\n    gl_FragColor.w = 1.0; //alpha;\n\n    //gl_FragColor = tex;\n}\n";

  vert = "\nprecision highp float;\n\nattribute vec3 aUV;\n\nuniform mat4 projMat;\nuniform mat4 modelViewMat;\nuniform mat3 cubeMat;\n\nvarying vec3 vNormal;\nvarying vec2 vUV;\n\nuniform vec4 uvRect;\nuniform sampler2D vertSampler;\nuniform vec3 camPos;\n\nconst float uvScalar = 4097.0 / 4096.0;\n\nvoid main(void) {\n	vec2 uv = aUV.xy * uvRect.zw + uvRect.xy;\n\n	vec3 aPos = vec3(uv * 2.0 - 1.0, 1.0);\n	aPos = normalize(aPos * cubeMat);\n\n	float height = texture2D(vertSampler, uv * uvScalar).a;\n	aPos *= 0.99 + (height - (uvRect.z * 3.0) * aUV.z) * 0.01;\n\n	vNormal = aPos;\n	vUV = uv.xy;\n\n	vec4 pos = vec4(aPos, 1.0);\n	pos = modelViewMat * pos;\n    gl_Position = projMat * pos;\n}\n";

  xgl.addProgram("planetNearMesh", vert, frag);

}).call(this);
