//@ sourceMappingURL=RandomStream.map
// Generated by CoffeeScript 1.6.1
(function() {
  var modulus, multiplier, offset, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  modulus = 4294967291;

  multiplier = 279470273;

  offset = 65537;

  root.RandomStream = (function() {

    function RandomStream(seed) {
      if (seed == null) {
        seed = 0;
      }
      this.seed = seed % modulus;
    }

    RandomStream.prototype.unit = function() {
      this.seed = ((this.seed + offset) * multiplier) % modulus;
      return this.seed / modulus;
    };

    RandomStream.prototype.intRange = function(min, max) {
      this.seed = ((this.seed + offset) * multiplier) % modulus;
      return this.seed % (max + 1 - min) + min;
    };

    RandomStream.prototype.symmetric = function() {
      return this.unit() * 2.0 - 1.0;
    };

    RandomStream.prototype.range = function(min, max) {
      return (max - min) * this.unit() + min;
    };

    RandomStream.prototype.radianAngle = function() {
      return this.range(0, 2.0 * Math.PI);
    };

    return RandomStream;

  })();

  root.randomIntFromSeed = function(number) {
    number = ((number + offset) * multiplier) % modulus;
    return number;
  };

}).call(this);
