//@ sourceMappingURL=RenderPlanetLowres.map
// Generated by CoffeeScript 1.6.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  ({
    initLowresPlanets: function() {},
    renderLowresPlanet: function(position, contentSeed) {}
  });

}).call(this);
