//@ sourceMappingURL=FarMapGeneratorShader.map
// Generated by CoffeeScript 1.6.1
(function() {
  var frag, i, vert, _i, _ref;

  frag = "precision highp float;\n\nvarying vec3 vPos;\nvarying vec3 vTangent;\nvarying vec3 vBinormal;\n\nuniform vec4 randomSeed;\n\n#define ONE_TEXEL (1.0/256.0)\n\n\nvec4 positionAndHeight(vec3 cubePos)\n{\n        vec3 pos = normalize(cubePos);\n        float h = heightFunc(pos, randomSeed);\n        pos *= 0.997 + h * 0.003;\n        return vec4(pos, h);\n}\n\n\nvoid main(void) {\n	vec4 h00 = positionAndHeight(vPos);\n        vec4 h10 = positionAndHeight(vPos + ONE_TEXEL * vBinormal);\n        vec4 h01 = positionAndHeight(vPos + ONE_TEXEL * vTangent);\n        \n        vec3 right = (h10.xyz - h00.xyz);\n        vec3 forward = (h01.xyz - h00.xyz);\n        vec3 normal = normalize(cross(right, forward));\n\n        float height = h00.a;\n        gl_FragColor = vec4((normal + 1.0) * 0.5, height);\n}\n";

  vert = "attribute vec2 aUV;\nattribute vec3 aPos;\nattribute vec3 aTangent;\nattribute vec3 aBinormal;\nvarying vec3 vPos;\nvarying vec3 vTangent;\nvarying vec3 vBinormal;\n\nvoid main(void) {\n	vPos = aPos;\n        vTangent = aTangent;\n        vBinormal = aBinormal;\n	gl_Position = vec4(aUV * 2.0 - 1.0, 0.0, 1.0);\n}\n";

  for (i = _i = 0, _ref = kosmosShaderHeightFunctions.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
    xgl.addProgram("farMapGenerator" + i, vert, xgl.commonNoiseShaderSource + kosmosShaderHeightFunctions[i] + frag);
  }

}).call(this);
