//@ sourceMappingURL=WindowsCompatibilityUglyHacks.map
// Generated by CoffeeScript 1.6.1
(function() {
  var is_windows, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.windowsCompatibilityUglyHacks = {};

  is_windows = (navigator.appVersion.indexOf("Win") !== -1 ? true : false);

  root.windowsCompatibilityUglyHacks.randomSeedDefString = !is_windows ? "uniform vec3 randomSeed;" : "const vec3 randomSeed = vec3(0.75, 0.5, 0.25);";

}).call(this);
